[package]
name = "codegen"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
tac = { path = "../tac" }
tacopt = { path = "../tacopt" }
bitset = { git = "https://github.com/MashPlant/bitset" }